name: deploy-pages
run-name: ${{ github.actor }} is deploying in Github Pages
on: 
  push:
    branches:
      - 'releases/**'
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: ls